### ISSUE TITLE
VgetRGB()/VsetRGB() should be called with the correct number of colors

### ISSUE THREAD

**Issue by sporniket** [freemint/tos.hyp#112]
References : a sequence of posts on atari forum [post 1 (sequence of calls does not work as expected)](https://www.atari-forum.com/viewtopic.php?p=438714#p438714) ; [post 2 (hypothesis)](https://www.atari-forum.com/viewtopic.php?p=438715#p438715) and [post 3(confirm that hypothesis is correct)](https://www.atari-forum.com/viewtopic.php?p=438717#p438717)

One should not try to save/restore more colors than supported by the video mode.

>Edit 
>location on the doc : https://freemint.github.io/tos.hyp/en/Screen_functions.html#VgetRGB

**Comment by mikrosk** [comment]
I think a better (more detailed) description would be helpful here. Although I am aware of this behaviour, I've been lazy to verify my hypothesis: is it because VgetRgb(256) reads 16 initialised colours + 240 random colours and then does the same with VsetRgb(256) but due to bank mirroring only the last 16 (garbage) colours are applied?
